### PR TITLE
added a few projects, reorderd with titles

### PR DESCRIPTION
**Pull request by shayaulman**
Nice project!
Feel free to remove/reorder anything...
Good Shabbos 😄

### CODE REVIEW

**Comment by binyamin** [comment]
I love the git shabbas one!

**Comment by binyamin** [comment]
@shayaulman I think github got confused about that second commit. Mind submitting a new PR?

**Comment by shayaulman** [comment]
Ha ha... I was wondering about that, interesting...
I'll do.

**Comment by shayaulman** [comment]
Here you go:
https://github.com/b3u/yidhub/pull/2

**Pull request merged**
